### ISSUE TITLE
mpt web editor does not request user to stay on page for dirty documents

### ISSUE THREAD

**Issue by payonel** [magik6k/MPT2#9]
the mpt web editor allows the user to leave a page of a dirty document.

expected; dirty document state is tracked, and a stay-on-page prompt is given to the user in the browser
actual: no prompt, leave is allowed, some work can be lost.

**Comment by magik6k** [comment]
this requires jwwf plugin hackery, but will do.

**Comment by magik6k** [comment]
Solved in v3, http://mpt.magik6k.net/
